// src/components/Form.vue
<script lang="ts">
export type NavigationState = 'idle' | 'submitting' | 'submitted' | 'error';

export interface Props {
    class: string;
    action: string;
    method: string;
}

export interface Events {
    (event: 'state', value: NavigationState): void;
    (event: 'optomisticData', value: FormData): void;
    (event: 'responseData', value: any): void;
    (event: 'error', value: Error): void;
}
</script>

<script setup lang="ts">
import { defineEmits, defineProps, onMounted } from 'vue';

const props = defineProps<Props>();
const emit = defineEmits<Events>();

onMounted(() => emit('state', 'idle'));

async function onSubmit($event: Event) {
    let form = $event.currentTarget as HTMLFormElement;
    let data = new FormData(form);

    emit('state', 'submitting');
    emit('optomisticData', data);

    let response = await fetch(form.action, {
        method: form.method,
        body: data,
    });

    if (!response.ok) {
        emit('state', 'error');
        emit('error', new Error(`${response.status}: ${response.statusText}`));
        return;
    }

    emit('state', 'submitted');
    emit('responseData', await response.json());

    emit('state', 'idle');
}
</script>

<template>
    <form v-bind="props" @submit.prevent="onSubmit($event)">
        <slot></slot>
    </form>
</template>

// src/components/Form.tsx
import type { FormEvent, ReactNode } from 'react';

export namespace Form {
    export type NavigationState = 'idle' | 'submitting' | 'submitted' | 'error';

    export interface Props {
        className?: string;
        action: string;
        method: string;

        children: ReactNode;

        onState?(value: NavigationState): void;
        onOptomisticData?(value: FormData): void;
        onResponseData?(value: any): void;
        onError?(value: Error): void;
    }
}

export function Form({ onState, onOptomisticData, onError, onResponseData, ...props }: Form.Props) {
    async function onSubmit($event: FormEvent<HTMLFormElement>) {
        $event.preventDefault();
        let form = $event.currentTarget;
        let data = new FormData(form);

        onState?.('submitting');
        onOptomisticData?.(data);

        let response = await fetch(form.action, {
            method: form.method,
            body: data,
        });

        if (!response.ok) {
            onState?.('error');
            onError?.(new Error(`${response.status}: ${response.statusText}`));
            return;
        }

        onState?.('submitted');
        onResponseData?.(await response.json());

        onState?.('idle');
    }

    return <form {...props} onSubmit={$event => onSubmit($event)} />;
}
